# Generated by Django 3.0.4 on 2020-03-10 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vocabulary', '__first__'),
        ('collection', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photograph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='', max_length=1000, null=True)),
                ('description', models.TextField(blank=True, max_length=10000)),
                ('image_path', models.CharField(max_length=800, null=True)),
                ('date_early', models.DateField(db_index=True)),
                ('date_late', models.DateField(db_index=True)),
                ('digitized_date', models.DateField()),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photographs', to='collection.Collection')),
                ('depicts', models.ManyToManyField(to='vocabulary.Person')),
                ('taken_by', models.ForeignKey(limit_choices_to='is_photographer', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photographs_taken', to='vocabulary.Person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('x_min', models.IntegerField()),
                ('x_max', models.IntegerField()),
                ('y_max', models.IntegerField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to=settings.AUTH_USER_MODEL)),
                ('person_depicted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='vocabulary.Person')),
                ('photograph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='photograph.Photograph')),
            ],
        ),
    ]
