# Generated by Django 3.0.5 on 2020-04-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photograph', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photograph',
            name='image_path',
            field=models.CharField(max_length=2000, unique=True),
        ),
    ]
