# Generated by Django 3.0.6 on 2020-06-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photograph', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='Date last modified (automatically recorded)'),
        ),
    ]
