# Generated by Django 3.0.7 on 2020-06-08 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photograph', '0002_auto_20200605_1044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photograph',
            options={'ordering': ['image_path']},
        ),
    ]
