# Generated by Django 3.0.7 on 2020-07-01 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photograph', '0003_auto_20200608_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.PositiveIntegerField(help_text='Number of pixels from the left side of the image')),
                ('width', models.PositiveIntegerField(help_text='Width of the region in pixes')),
                ('y', models.PositiveIntegerField(help_text='Number of pixels from the top side of the image')),
                ('height', models.PositiveIntegerField(help_text='Height of the region in pixes')),
                ('photograph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='photograph.Photograph')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Annotation',
        ),
    ]
