# Generated by Django 3.0.7 on 2020-07-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photograph', '0005_auto_20200701_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photograph',
            name='image_path',
            field=models.CharField(db_index=True, editable=False, help_text='Base path for the image on the IIIF server', max_length=2000, unique=True),
        ),
    ]
