# Generated by Django 3.0.7 on 2020-07-04 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photograph', '0007_auto_20200703_0657'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectAnnotationLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Unique short readable label', max_length=400, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='faceannotation',
            name='photograph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faceannotation', to='photograph.Photograph'),
        ),
        migrations.CreateModel(
            name='ObjectAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.PositiveIntegerField(help_text='Number of pixels from the left side of the image')),
                ('width', models.PositiveIntegerField(help_text='Width of the region in pixes')),
                ('y', models.PositiveIntegerField(help_text='Number of pixels from the top side of the image')),
                ('height', models.PositiveIntegerField(help_text='Height of the region in pixes')),
                ('score', models.FloatField()),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='photograph.ObjectAnnotationLabel')),
                ('photograph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectannotation', to='photograph.Photograph')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
