# Generated by Django 3.0.7 on 2020-07-15 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photograph', '0008_auto_20200703_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Unique short readable label', max_length=400, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhotoLabelAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(db_index=True)),
                ('topicality', models.FloatField(db_index=True)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='photograph.PhotoLabel')),
                ('photograph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_annotations', to='photograph.Photograph')),
            ],
        ),
    ]
