# Generated by Django 3.0.7 on 2020-08-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photograph', '0011_auto_20200720_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photograph',
            name='height',
            field=models.PositiveIntegerField(default=0, help_text='The height of the original image in pixels'),
        ),
        migrations.AlterField(
            model_name='photograph',
            name='width',
            field=models.PositiveIntegerField(default=0, help_text='The width of the original image in pixels'),
        ),
    ]
