# Generated by Django 3.0.7 on 2020-08-05 14:10

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photograph', '0012_auto_20200805_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photograph',
            name='image_search_text',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, help_text='The GIN index field in postgres for the image_text field, allowing for simplistic full text search of recognized text in photographs.', null=True),
        ),
    ]
