# Generated by Django 3.0.7 on 2020-06-23 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagging', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['label']},
        ),
        migrations.AlterField(
            model_name='tag',
            name='label',
            field=models.CharField(help_text='Unique short readable label', max_length=400, unique=True),
        ),
    ]
