# Generated by Django 3.0.7 on 2020-06-24 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0021_closematchset_has_duplicates'),
        ('photograph', '0003_auto_20200608_1103'),
        ('tagging', '0002_auto_20200623_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taggingdecision',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='taggingtask',
            name='description',
        ),
        migrations.RemoveField(
            model_name='taggingtask',
            name='last_updated',
        ),
        migrations.AlterField(
            model_name='taggingdecision',
            name='photograph',
            field=models.ForeignKey(help_text='The photograph this tagging decision applies to', on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='photograph.Photograph'),
        ),
        migrations.AlterField(
            model_name='taggingdecision',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='tagging.TaggingTask'),
        ),
        migrations.AlterField(
            model_name='taggingtask',
            name='pytorch_model',
            field=models.ForeignKey(help_text='The CV model associated with this tagging task', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='cv.PyTorchModel'),
        ),
        migrations.AlterField(
            model_name='taggingtask',
            name='tag',
            field=models.ForeignKey(help_text='The vocabulary tag to be applied when working this task', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tagging.Tag'),
        ),
    ]
