# Generated by Django 3.0.7 on 2020-06-24 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photograph', '0003_auto_20200608_1103'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tagging', '0003_auto_20200624_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotographTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date created (automatically recorded)')),
                ('last_updated', models.DateTimeField(auto_now=True, db_index=True, help_text='Date last modified (automatically recorded)')),
                ('photograph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photograph_tags', to='photograph.Photograph')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photograph_tags', to='tagging.Tag')),
                ('user_last_modified', models.ForeignKey(editable=False, help_text='Last modified by user', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='photographtags_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('photograph', 'tag')},
            },
        ),
    ]
