# Generated by Django 3.0.4 on 2020-03-10 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='', max_length=1000, null=True)),
                ('description', models.TextField(blank=True, max_length=10000)),
                ('first_name', models.CharField(blank=True, max_length=800, null=True)),
                ('last_name', models.CharField(blank=True, db_index=True, max_length=800, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='', max_length=1000, null=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='vocabulary.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
