version: "3"
services:
  rest:
    build: rest
    restart: always
    command: "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./rest:/vol/app:z
      - ./data/cv/indices:${DIST_INDICES_PATH}:z
      - ./data/import:/vol/data:z
      - static:/vol/static_files:z
    expose:
      - 8000
    ports:
      - "25:25"
    links:
      - "postgres:postgres"
    env_file: .env
    depends_on:
      - postgres

  postgres:
    image: postgres:12.2
    restart: always
    volumes:
      - ../campi_db:/var/lib/postgresql/data:z
    expose:
      - 5432
    env_file: .env

  nginx:
    image: nginx:1.16.1
    restart: always
    links:
      - "rest:rest"
    volumes:
      - ./nginx:/etc/nginx/conf.d/.
      - ./data/logs:/var/log/nginx
      - ./vue/dist:/vol/vue
      - static:/vol/static_files
    ports:
      - "80:80"
      - "443:443"
    env_file: .env
    depends_on:
      - rest

volumes:
  static:
