# Generated by Django 3.0.7 on 2020-06-11 18:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photograph', '0003_auto_20200608_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='GCVResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', django.contrib.postgres.fields.jsonb.JSONField()),
                ('photograph', models.OneToOneField(help_text='Source photograph for this response', on_delete=django.db.models.deletion.CASCADE, related_name='gcv_response', to='photograph.Photograph')),
            ],
        ),
    ]
