# Generated by Django 3.0.7 on 2020-06-12 11:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gcv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gcvresponse',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, help_text='Date created (automatically recorded)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gcvresponse',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='Date last modified (automatically recorded)'),
        ),
    ]
