# Generated by Django 3.0.7 on 2020-07-01 17:51

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gcv', '0002_auto_20200612_0754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gcvresponse',
            name='json',
        ),
        migrations.RemoveField(
            model_name='gcvresponse',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='gcvresponse',
            name='annotations',
            field=picklefield.fields.PickledObjectField(editable=False, null=True),
        ),
    ]
