# Generated by Django 3.0.5 on 2020-04-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photograph', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Embeddings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=10000)),
                ('embeddings_file', models.FilePathField(null=True, path='/vol/cv/matrices')),
                ('index_file', models.FilePathField(null=True, path='/vol/cv/indices')),
                ('photographs', models.ManyToManyField(related_name='cv_models', to='photograph.Photograph')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
