# Generated by Django 3.0.5 on 2020-04-08 15:12

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photograph', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Embeddings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=1000, unique=True)),
                ('description', models.TextField(blank=True, max_length=10000)),
                ('embeddings_file', models.FilePathField(null=True, path='/vol/cv/embeddings')),
                ('index_file', models.FilePathField(null=True, path='/vol/cv/indices')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhotographEmbeddings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(db_index=True)),
                ('array', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=None)),
                ('embeddings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photograph_embeddings', to='cv.Embeddings')),
                ('photograph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photograph_embeddings', to='photograph.Photograph')),
            ],
            options={
                'ordering': ['embeddings', 'sequence'],
                'unique_together': {('embeddings', 'photograph'), ('embeddings', 'sequence')},
            },
        ),
        migrations.AddField(
            model_name='embeddings',
            name='photographs',
            field=models.ManyToManyField(related_name='cv_models', through='cv.PhotographEmbeddings', to='photograph.Photograph'),
        ),
    ]
