# Generated by Django 3.0.6 on 2020-06-04 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photograph', '0001_initial'),
        ('cv', '0003_auto_20200603_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloseMatchRunConsidered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('close_match_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='considered_photo_membership', to='cv.CloseMatchRun')),
                ('photograph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='considered_photo_membership', to='photograph.Photograph')),
            ],
            options={
                'unique_together': {('close_match_run', 'photograph')},
            },
        ),
        migrations.AddField(
            model_name='closematchrun',
            name='considered_photos',
            field=models.ManyToManyField(through='cv.CloseMatchRunConsidered', to='photograph.Photograph'),
        ),
    ]
