# Generated by Django 3.0.6 on 2020-06-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photograph', '0001_initial'),
        ('cv', '0004_auto_20200604_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closematchrun',
            name='considered_photos',
            field=models.ManyToManyField(related_name='considered_by_run', through='cv.CloseMatchRunConsidered', to='photograph.Photograph'),
        ),
    ]
