# Generated by Django 3.0.6 on 2020-06-05 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photograph', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cv', '0005_auto_20200604_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='closematchset',
            name='photographs',
            field=models.ManyToManyField(through='cv.CloseMatchSetMembership', to='photograph.Photograph'),
        ),
        migrations.AddField(
            model_name='closematchset',
            name='user_last_modified',
            field=models.ForeignKey(editable=False, help_text='Last modified by user', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closematchsets_modified', to=settings.AUTH_USER_MODEL),
        ),
    ]
