# Generated by Django 3.0.6 on 2020-06-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0006_auto_20200605_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closematchrun',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='Date last modified (automatically recorded)'),
        ),
        migrations.AlterField(
            model_name='closematchset',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='Date last modified (automatically recorded)'),
        ),
        migrations.AlterField(
            model_name='pytorchmodel',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='Date last modified (automatically recorded)'),
        ),
    ]
