# Generated by Django 3.0.6 on 2020-06-05 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photograph', '0002_auto_20200605_1044'),
        ('cv', '0007_auto_20200605_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='closematchset',
            name='representative_photograph',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='representative_of_sets', to='photograph.Photograph'),
        ),
        migrations.AddField(
            model_name='closematchsetmembership',
            name='accepted',
            field=models.NullBooleanField(default=None, help_text='Has this membership been validated by an editor?'),
        ),
    ]
