# Generated by Django 3.0.7 on 2020-06-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0008_auto_20200605_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='closematchset',
            name='invalid',
            field=models.BooleanField(db_index=True, default=False, help_text='Has this set been rendered redundant because its seed photograph has been matched to another set, or because its member photos have all been matched to sets?'),
        ),
        migrations.AddField(
            model_name='closematchsetmembership',
            name='invalid',
            field=models.BooleanField(db_index=True, default=False, help_text='Has this member photo already been matched in another set?'),
        ),
    ]
