# Generated by Django 3.0.7 on 2020-06-10 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photograph', '0003_auto_20200608_1103'),
        ('cv', '0010_bitonalinceptionv3_colorinceptionv3_grayinceptionv3'),
    ]

    operations = [
        migrations.AddField(
            model_name='closematchrun',
            name='min_samples',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='closematchrun',
            name='annoy_idx',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='close_match_runs', to='cv.AnnoyIdx'),
        ),
        migrations.AlterField(
            model_name='closematchset',
            name='seed_photograph',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seeded_close_match_sets', to='photograph.Photograph'),
        ),
    ]
