# Generated by Django 3.0.7 on 2020-06-11 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0011_auto_20200610_1316'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='closematchrun',
            unique_together={('pytorch_model', 'cutoff_distance', 'exclude_future_distance')},
        ),
        migrations.RemoveField(
            model_name='closematchrun',
            name='annoy_idx',
        ),
        migrations.RemoveField(
            model_name='closematchrun',
            name='considered_photos',
        ),
        migrations.RemoveField(
            model_name='closematchrun',
            name='max_neighbors',
        ),
    ]
