# Generated by Django 3.0.7 on 2020-06-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0012_auto_20200611_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closematchrun',
            name='min_samples',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterUniqueTogether(
            name='closematchrun',
            unique_together={('pytorch_model', 'cutoff_distance', 'exclude_future_distance', 'min_samples')},
        ),
    ]
