# Generated by Django 3.0.7 on 2020-06-12 15:04

from django.db import migrations, models


def transfer_distances(apps, schema_editor):
    # If a conference has an abbreviation, use it to replace the short_title
    CloseMatchSetMembership = apps.get_model("cv", "CloseMatchSetMembership")
    CloseMatchSetMembership.objects.filter(distance=0.1).update(core=True)
    CloseMatchSetMembership.objects.filter(distance=0.2).update(core=False)


class Migration(migrations.Migration):

    dependencies = [("cv", "0014_auto_20200611_1232")]

    operations = [
        migrations.AddField(
            model_name="closematchsetmembership",
            name="core",
            field=models.BooleanField(
                default=True,
                help_text="Is this membership part of the core cluster or added in the second pass?",
            ),
        ),
        migrations.RunPython(transfer_distances),
    ]
