# Generated by Django 3.0.7 on 2020-06-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0016_auto_20200612_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='closematchsetmembership',
            name='distance',
            field=models.FloatField(db_index=True, default=0.0, help_text='Cosine distance from the first membership added to this set'),
        ),
    ]
