# Generated by Django 3.0.7 on 2020-06-14 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0017_closematchsetmembership_distance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='closematchset',
            name='invalid',
        ),
    ]
