# Generated by Django 3.0.7 on 2020-06-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0020_auto_20200619_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='closematchset',
            name='has_duplicates',
            field=models.BooleanField(default=False, help_text='Does this set contain exact duplicates / copy-negatives?'),
        ),
    ]
