# Generated by Django 3.0.7 on 2020-06-25 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photograph', '0003_auto_20200608_1103'),
        ('cv', '0021_closematchset_has_duplicates'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullDistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField(db_index=True)),
                ('photograph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_distances', to='photograph.Photograph')),
                ('pytorch_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='full_distances', to='cv.PyTorchModel')),
                ('target_photograph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_distances', to='photograph.Photograph')),
            ],
            options={
                'ordering': ['distance'],
                'unique_together': {('photograph', 'target_photograph', 'pytorch_model')},
            },
        ),
    ]
