# Generated by Django 3.0.7 on 2020-06-26 15:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0021_closematchset_has_duplicates'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='indexembedding',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='indexembedding',
            name='annoy_idx',
        ),
        migrations.RemoveField(
            model_name='indexembedding',
            name='embedding',
        ),
        migrations.AddField(
            model_name='pytorchmodel',
            name='annoy_idx_file',
            field=models.FilePathField(blank=True, null=True, path='/vol/cv/indices', unique=True),
        ),
        migrations.AddField(
            model_name='pytorchmodel',
            name='photo_indices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), null=True, size=None),
        ),
        migrations.DeleteModel(
            name='AnnoyIdx',
        ),
        migrations.DeleteModel(
            name='IndexEmbedding',
        ),
    ]
