# Generated by Django 3.0.7 on 2020-07-01 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0022_auto_20200626_1101'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CloseMatchRunConsidered',
        ),
    ]
