# Generated by Django 3.0.7 on 2020-08-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0024_resnet18'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closematchrun',
            name='min_samples',
            field=models.PositiveIntegerField(default=2, help_text='Minimum number of samples needed to create a cluster. 2 should almost always be the default, since in our case we will want to surface groups as small as 2 paris of duplicate photos.'),
        ),
    ]
