# Generated by Django 3.0.5 on 2020-04-26 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', max_length=1000)),
                ('parent_collection', models.ForeignKey(help_text='The immediate parent of this collection', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_collections', to='collection.Collection')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
