# Generated by Django 3.0.5 on 2020-05-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_code',
            field=models.CharField(blank=True, help_text='custom code used for this job', max_length=20, unique=True),
        ),
    ]
