# Generated by Django 3.0.7 on 2020-08-05 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_auto_20200527_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobtag',
            name='user_last_modified',
        ),
        migrations.RemoveField(
            model_name='job',
            name='tags',
        ),
        migrations.DeleteModel(
            name='JobsTags',
        ),
        migrations.DeleteModel(
            name='JobTag',
        ),
    ]
